project_id         = "yash-cloud"
region             = "us-east1"
zone               = "us-east1-b"
tf_service_account = "sa-webapp-tf-cicd@yash-cloud.iam.gserviceaccount.com"
gcp_key_path       = "/Users/yashashreepatel/Desktop/NEU/Spring 2024/Cloud/Github/yash-cloud-key.json"
